name: brofinance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  fluttertoast: ^8.0.8
  http: ^0.13.4
  shared_preferences: ^2.0.11
  js: ^0.6.3
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
     - assets/images/logo.png
     - assets/images/btc.png
     - assets/images/usdt.png
     - assets/images/eth.png
     - assets/images/bnb.png
     - assets/images/ada.png
     - assets/images/mana.png
     - assets/images/sand.png
     - assets/images/avax.png
     - assets/images/sol.png


  fonts:
     - family: AlfaSlab
       fonts:
         - asset: assets/fonts/AlfaSlabOne-Regular.ttf
     - family: BebasNeue
       fonts:
         - asset: assets/fonts/BebasNeue-Regular.ttf

